GET http://localhost:8080/api/dashboard/analysis
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiI1MTk4MDIwYjNkMzg0ZmRhOTZhODk3ZmFjNTNiODU2MiIsInRpZCI6MjAwMzcyOTEzMTc1NDYyMjk3NywiYWNjIjoieGlhb3l1In0.8a7XbBSfb0UFloeaBAA4c1PQgmyeCBMdwhPnOrKNNuE8TB2JceKSka5IqRVLZAQGUhGp3ebjdvzsJ7mMHckobQ
